#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "Mcu_HW.h"

#include "PORT_Cfg.h"
#include "PORT.h"



void PORT_Init(){
 u8 Local_u8Temp = 0;
GPIOA->DEN =0xFF;GPIOB->DEN =0xFF;GPIOC->DEN =0xFF;GPIOD->DEN =0xFF;GPIOE->DEN =0xFF;GPIOF->DEN =0xFF;
	
GPIOA->DIR = PRIVATE_u8_CONC(PORT_PA7_DIRECTION,PORT_PA6_DIRECTION,PORT_PA5_DIRECTION,PORT_PA4_DIRECTION,
		PORT_PA3_DIRECTION,PORT_PA2_DIRECTION,PORT_PA1_DIRECTION,PORT_PA0_DIRECTION);
GPIOA->DATA[255] = PRIVATE_u8_CONC(PORT_PA7_LEVEL,PORT_PA6_LEVEL,PORT_PA5_LEVEL,PORT_PA4_LEVEL,
		PORT_PA3_LEVEL,PORT_PA2_LEVEL,PORT_PA1_LEVEL,PORT_PA0_LEVEL);
GPIOA->ODR = PRIVATE_u8_CONC(PORT_PA7_ODrConfig,PORT_PA6_ODrConfig,PORT_PA5_ODrConfig,PORT_PA4_ODrConfig,
		PORT_PA3_ODrConfig,PORT_PA2_ODrConfig,PORT_PA1_ODrConfig,PORT_PA0_ODrConfig);
	
GPIOB->DIR = PRIVATE_u8_CONC(PORT_PB7_DIRECTION,PORT_PB6_DIRECTION,PORT_PB5_DIRECTION,PORT_PB4_DIRECTION,
		PORT_PB3_DIRECTION,PORT_PB2_DIRECTION,PORT_PB1_DIRECTION,PORT_PB0_DIRECTION);
GPIOB->DATA[255] = PRIVATE_u8_CONC(PORT_PB7_LEVEL,PORT_PB6_LEVEL,PORT_PB5_LEVEL,PORT_PB4_LEVEL,
		PORT_PB3_LEVEL,PORT_PB2_LEVEL,PORT_PB1_LEVEL,PORT_PB0_LEVEL);	
GPIOB->ODR = PRIVATE_u8_CONC(PORT_PB7_ODrConfig,PORT_PB6_ODrConfig,PORT_PB5_ODrConfig,PORT_PB4_ODrConfig,
		PORT_PB3_ODrConfig,PORT_PB2_ODrConfig,PORT_PB1_ODrConfig,PORT_PB0_ODrConfig);	
	
GPIOC->DIR = PRIVATE_u8_CONC(PORT_PC7_DIRECTION,PORT_PC6_DIRECTION,PORT_PC5_DIRECTION,PORT_PC4_DIRECTION,
		PORT_PC3_DIRECTION,PORT_PC2_DIRECTION,PORT_PC1_DIRECTION,PORT_PC0_DIRECTION);
GPIOC->DATA[255] = PRIVATE_u8_CONC(PORT_PC7_LEVEL,PORT_PC6_LEVEL,PORT_PC5_LEVEL,PORT_PC4_LEVEL,
		PORT_PC3_LEVEL,PORT_PC2_LEVEL,PORT_PC1_LEVEL,PORT_PC0_LEVEL);	
GPIOC->ODR = PRIVATE_u8_CONC(PORT_PC7_ODrConfig,PORT_PC6_ODrConfig,PORT_PC5_ODrConfig,PORT_PC4_ODrConfig,
		PORT_PC3_ODrConfig,PORT_PC2_ODrConfig,PORT_PC1_ODrConfig,PORT_PC0_ODrConfig);		
	
GPIOD->DIR = PRIVATE_u8_CONC(PORT_PD7_DIRECTION,PORT_PD6_DIRECTION,PORT_PD5_DIRECTION,PORT_PD4_DIRECTION,
		PORT_PD3_DIRECTION,PORT_PD2_DIRECTION,PORT_PD1_DIRECTION,PORT_PD0_DIRECTION);
GPIOD->DATA[255] = PRIVATE_u8_CONC(PORT_PD7_LEVEL,PORT_PD6_LEVEL,PORT_PD5_LEVEL,PORT_PD4_LEVEL,
		PORT_PD3_LEVEL,PORT_PD2_LEVEL,PORT_PD1_LEVEL,PORT_PD0_LEVEL);	
GPIOD->ODR = PRIVATE_u8_CONC(PORT_PD7_ODrConfig,PORT_PD6_ODrConfig,PORT_PD5_ODrConfig,PORT_PD4_ODrConfig,
		PORT_PD3_ODrConfig,PORT_PD2_ODrConfig,PORT_PD1_ODrConfig,PORT_PD0_ODrConfig);		
		
GPIOE->DIR = PRIVATE_u8_CONC(0,0,PORT_PE5_DIRECTION,PORT_PE4_DIRECTION,
		PORT_PE3_DIRECTION,PORT_PE2_DIRECTION,PORT_PE1_DIRECTION,PORT_PE0_DIRECTION);
GPIOE->DATA[255] = PRIVATE_u8_CONC(0,0,PORT_PE5_LEVEL,PORT_PE4_LEVEL,
		PORT_PE3_LEVEL,PORT_PE2_LEVEL,PORT_PE1_LEVEL,PORT_PE0_LEVEL);		
GPIOE->ODR = PRIVATE_u8_CONC(0,0,PORT_PE5_ODrConfig,PORT_PE4_ODrConfig,
		PORT_PE3_ODrConfig,PORT_PE2_ODrConfig,PORT_PE1_ODrConfig,PORT_PE0_ODrConfig);		
		
GPIOF->DIR = PRIVATE_u8_CONC(0,0,0,PORT_PF4_DIRECTION,
		PORT_PF3_DIRECTION,PORT_PF2_DIRECTION,PORT_PF1_DIRECTION,PORT_PF0_DIRECTION);		
GPIOF->DATA[255] = PRIVATE_u8_CONC(0,0,0,PORT_PF4_LEVEL,
		PORT_PF3_LEVEL,PORT_PF2_LEVEL,PORT_PF1_LEVEL,PORT_PF0_LEVEL);	
GPIOF->ODR = PRIVATE_u8_CONC(0,0,0,PORT_PF4_ODrConfig,
		PORT_PF3_ODrConfig,PORT_PF2_ODrConfig,PORT_PF1_ODrConfig,PORT_PF0_ODrConfig);





	






		
		

#if PORT_PA_OutCurrent == PORT_INIT_8mA
GPIOA->DR8R = 0xFF;
#elif 	PORT_PA_OutCurrent == PORT_INIT_4mA
GPIOA->DR4R = 0xFF;
#else
GPIOA->DR2R = 0xFF;	
#endif
#if PORT_PB_OutCurrent == PORT_INIT_8mA
GPIOB->DR2R = 0xFF;
#elif 	PORT_PB_OutCurrent == PORT_INIT_4mA
GPIOB->DR2R = 0xFF;
#else
GPIOB->DR2R = 0xFF;	
#endif
#if PORT_PC_OutCurrent == PORT_INIT_8mA
GPIOC->DR2R = 0xFF;
#elif 	PORT_PC_OutCurrent == PORT_INIT_4mA
GPIOC->DR2R = 0xFF;
#else
GPIOC->DR2R = 0xFF;	
#endif
#if PORT_PD_OutCurrent == PORT_INIT_8mA
GPIOD->DR2R = 0xFF;
#elif 	PORT_PD_OutCurrent == PORT_INIT_4mA
GPIOD->DR2R = 0xFF;
#else
GPIOD->DR2R = 0xFF;	
#endif
#if PORT_PE_OutCurrent == PORT_INIT_8mA
GPIOE->DR2R = 0xFF;
#elif 	PORT_PE_OutCurrent == PORT_INIT_4mA
GPIOE->DR2R = 0xFF;
#else
GPIOE->DR2R = 0xFF;	
#endif
#if PORT_PF_OutCurrent == PORT_INIT_8mA
GPIOF->DR2R = 0xFF;
#elif 	PORT_PF_OutCurrent == PORT_INIT_4mA
GPIOF->DR2R = 0xFF;
#else
GPIOF->DR2R = 0xFF;	
#endif
	
	
}
