#ifndef PORT_CFG_H_
#define PORT_CFG_H_

/***********Direction Configuration **************/
/*Options: 1-PORT_INIT_INPUT    2-PORT_INIT_OUTPUT */
#define PORT_PA0_DIRECTION 	  PORT_INIT_OUTPUT
#define PORT_PA1_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PA2_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PA3_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PA4_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PA5_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PA6_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PA7_DIRECTION 	  PORT_INIT_INPUT

#define PORT_PB0_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PB1_DIRECTION 	  PORT_INIT_OUTPUT
#define PORT_PB2_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PB3_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PB4_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PB5_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PB6_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PB7_DIRECTION 	  PORT_INIT_INPUT

#define PORT_PC0_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PC1_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PC2_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PC3_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PC4_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PC5_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PC6_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PC7_DIRECTION 	  PORT_INIT_INPUT

#define PORT_PD0_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PD1_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PD2_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PD3_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PD4_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PD5_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PD6_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PD7_DIRECTION 	  PORT_INIT_INPUT

#define PORT_PE0_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PE1_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PE2_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PE3_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PE4_DIRECTION 	  PORT_INIT_INPUT
#define PORT_PE5_DIRECTION 	  PORT_INIT_INPUT


#define PORT_PF0_DIRECTION 	  PORT_INIT_OUTPUT
#define PORT_PF1_DIRECTION 	  PORT_INIT_OUTPUT
#define PORT_PF2_DIRECTION 	  PORT_INIT_OUTPUT
#define PORT_PF3_DIRECTION 	  PORT_INIT_OUTPUT
#define PORT_PF4_DIRECTION 	  PORT_INIT_INPUT
/********************************************/
/********* Pin Level Configuration***********/
/*Options: 1-PORT_INIT_HIGH		2-PORT_INIT_LOW*/

#define PORT_PA0_LEVEL	  PORT_INIT_HIGH
#define PORT_PA1_LEVEL	  PORT_INIT_LOW
#define PORT_PA2_LEVEL	  PORT_INIT_LOW
#define PORT_PA3_LEVEL	  PORT_INIT_LOW
#define PORT_PA4_LEVEL	  PORT_INIT_LOW
#define PORT_PA5_LEVEL	  PORT_INIT_LOW
#define PORT_PA6_LEVEL	  PORT_INIT_LOW
#define PORT_PA7_LEVEL	  PORT_INIT_LOW

#define PORT_PB0_LEVEL	  PORT_INIT_LOW
#define PORT_PB1_LEVEL	  PORT_INIT_HIGH
#define PORT_PB2_LEVEL	  PORT_INIT_LOW
#define PORT_PB3_LEVEL	  PORT_INIT_LOW
#define PORT_PB4_LEVEL	  PORT_INIT_LOW
#define PORT_PB5_LEVEL	  PORT_INIT_LOW
#define PORT_PB6_LEVEL	  PORT_INIT_LOW
#define PORT_PB7_LEVEL	  PORT_INIT_LOW

#define PORT_PC0_LEVEL	  PORT_INIT_LOW
#define PORT_PC1_LEVEL	  PORT_INIT_LOW
#define PORT_PC2_LEVEL	  PORT_INIT_LOW
#define PORT_PC3_LEVEL	  PORT_INIT_LOW
#define PORT_PC4_LEVEL	  PORT_INIT_LOW
#define PORT_PC5_LEVEL	  PORT_INIT_LOW
#define PORT_PC6_LEVEL	  PORT_INIT_LOW
#define PORT_PC7_LEVEL	  PORT_INIT_LOW

#define PORT_PD0_LEVEL	  PORT_INIT_LOW
#define PORT_PD1_LEVEL	  PORT_INIT_LOW
#define PORT_PD2_LEVEL	  PORT_INIT_LOW
#define PORT_PD3_LEVEL	  PORT_INIT_LOW
#define PORT_PD4_LEVEL	  PORT_INIT_LOW
#define PORT_PD5_LEVEL	  PORT_INIT_LOW
#define PORT_PD6_LEVEL	  PORT_INIT_LOW
#define PORT_PD7_LEVEL	  PORT_INIT_LOW

#define PORT_PE0_LEVEL	  PORT_INIT_LOW
#define PORT_PE1_LEVEL	  PORT_INIT_LOW
#define PORT_PE2_LEVEL	  PORT_INIT_LOW
#define PORT_PE3_LEVEL	  PORT_INIT_LOW
#define PORT_PE4_LEVEL	  PORT_INIT_LOW
#define PORT_PE5_LEVEL	  PORT_INIT_LOW


#define PORT_PF0_LEVEL	  PORT_INIT_HIGH
#define PORT_PF1_LEVEL	  PORT_INIT_HIGH
#define PORT_PF2_LEVEL	  PORT_INIT_HIGH
#define PORT_PF3_LEVEL	  PORT_INIT_HIGH
#define PORT_PF4_LEVEL	  PORT_INIT_LOW

/********************************************/
/*******Output Current Configuration*********/
/*Options: 1-PORT_INIT_2mA    2-PORT_INIT_4mA     3-PORT_INIT_8mA*/

#define PORT_PA_OutCurrent	  PORT_INIT_2mA

#define PORT_PB_OutCurrent	  PORT_INIT_2mA

#define PORT_PC_OutCurrent	  PORT_INIT_2mA

#define PORT_PD_OutCurrent	  PORT_INIT_2mA

#define PORT_PE_OutCurrent	  PORT_INIT_2mA

#define PORT_PF_OutCurrent	  PORT_INIT_2mA

/********************************************/
/*******Pin Attachment Configuration*********/
/*Options: 1-PORT_INIT_PP    2-PORT_INIT_OD */

#define PORT_PA0_ODrConfig	  PORT_INIT_PP
#define PORT_PA1_ODrConfig	  PORT_INIT_PP
#define PORT_PA2_ODrConfig	  PORT_INIT_PP
#define PORT_PA3_ODrConfig	  PORT_INIT_PP
#define PORT_PA4_ODrConfig	  PORT_INIT_PP
#define PORT_PA5_ODrConfig	  PORT_INIT_PP
#define PORT_PA6_ODrConfig	  PORT_INIT_OD
#define PORT_PA7_ODrConfig	  PORT_INIT_PP
                                
#define PORT_PB0_ODrConfig	  PORT_INIT_PP
#define PORT_PB1_ODrConfig	  PORT_INIT_PP
#define PORT_PB2_ODrConfig	  PORT_INIT_PP
#define PORT_PB3_ODrConfig	  PORT_INIT_PP
#define PORT_PB4_ODrConfig	  PORT_INIT_PP
#define PORT_PB5_ODrConfig	  PORT_INIT_PP
#define PORT_PB6_ODrConfig	  PORT_INIT_PP
#define PORT_PB7_ODrConfig	  PORT_INIT_PP
                               
#define PORT_PC0_ODrConfig	  PORT_INIT_PP
#define PORT_PC1_ODrConfig	  PORT_INIT_PP
#define PORT_PC2_ODrConfig	  PORT_INIT_PP
#define PORT_PC3_ODrConfig	  PORT_INIT_PP
#define PORT_PC4_ODrConfig	  PORT_INIT_PP
#define PORT_PC5_ODrConfig	  PORT_INIT_PP
#define PORT_PC6_ODrConfig	  PORT_INIT_PP
#define PORT_PC7_ODrConfig	  PORT_INIT_PP
          
#define PORT_PD0_ODrConfig	  PORT_INIT_PP
#define PORT_PD1_ODrConfig	  PORT_INIT_PP
#define PORT_PD2_ODrConfig	  PORT_INIT_PP
#define PORT_PD3_ODrConfig	  PORT_INIT_PP
#define PORT_PD4_ODrConfig	  PORT_INIT_PP
#define PORT_PD5_ODrConfig	  PORT_INIT_PP
#define PORT_PD6_ODrConfig	  PORT_INIT_PP
#define PORT_PD7_ODrConfig	  PORT_INIT_PP
          
#define PORT_PE0_ODrConfig	  PORT_INIT_PP
#define PORT_PE1_ODrConfig	  PORT_INIT_PP
#define PORT_PE2_ODrConfig	  PORT_INIT_PP
#define PORT_PE3_ODrConfig	  PORT_INIT_PP
#define PORT_PE4_ODrConfig	  PORT_INIT_PP
#define PORT_PE5_ODrConfig	  PORT_INIT_PP
          
          
#define PORT_PF0_ODrConfig	  PORT_INIT_PP
#define PORT_PF1_ODrConfig	  PORT_INIT_PP
#define PORT_PF2_ODrConfig	  PORT_INIT_PP
#define PORT_PF3_ODrConfig	  PORT_INIT_PP
#define PORT_PF4_ODrConfig	  PORT_INIT_PP














#endif